<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="5" passed="4">
  <reporter-output>
    <line>
      <![CDATA[F:\workspace\test/testReport/failScreen/web/20151130-224707-174_test000login.png]]>
    </line>
    <line>
      <![CDATA[<img src="../F:\workspace\test/testReport/failScreen/web/20151130-224707-174_test000login.png"/>]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="17193" started-at="2015-11-30T14:46:53Z" finished-at="2015-11-30T14:47:10Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="17193" started-at="2015-11-30T14:46:53Z" finished-at="2015-11-30T14:47:10Z">
      <class name="projects.ticket.testCases.ticketWeb.baShi">
        <test-method status="PASS" signature="setUp()[pri:0, instance:projects.ticket.testCases.ticketWeb.baShi@5594a1b5]" name="setUp" is-config="true" duration-ms="2512" started-at="2015-11-30T22:46:53Z" finished-at="2015-11-30T22:46:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="test000login()[pri:0, instance:projects.ticket.testCases.ticketWeb.baShi@5594a1b5]" name="test000login" duration-ms="5794" started-at="2015-11-30T22:46:56Z" finished-at="2015-11-30T22:47:02Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [333334] but found [333]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [333334] but found [333]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at test.autotest.core.UI.assertEquals(UI.java:125)
	at projects.ticket.testCases.ticketWeb.baShi.test000login(baShi.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[F:\workspace\test/testReport/failScreen/web/20151130-224707-174_test000login.png]]>
            </line>
            <line>
              <![CDATA[<img src="../F:\workspace\test/testReport/failScreen/web/20151130-224707-174_test000login.png"/>]]>
            </line>
          </reporter-output>
        </test-method> <!-- test000login -->
        <test-method status="PASS" signature="test001EnterBusStationPage()[pri:0, instance:projects.ticket.testCases.ticketWeb.baShi@5594a1b5]" name="test001EnterBusStationPage" duration-ms="404" started-at="2015-11-30T22:47:07Z" finished-at="2015-11-30T22:47:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test001EnterBusStationPage -->
        <test-method status="PASS" signature="test002login()[pri:0, instance:projects.ticket.testCases.ticketWeb.baShi@5594a1b5]" name="test002login" duration-ms="1" started-at="2015-11-30T22:47:07Z" finished-at="2015-11-30T22:47:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test002login -->
        <test-method status="PASS" signature="test003login()[pri:0, instance:projects.ticket.testCases.ticketWeb.baShi@5594a1b5]" name="test003login" duration-ms="1" started-at="2015-11-30T22:47:07Z" finished-at="2015-11-30T22:47:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test003login -->
        <test-method status="PASS" signature="test004login()[pri:0, instance:projects.ticket.testCases.ticketWeb.baShi@5594a1b5]" name="test004login" duration-ms="1585" started-at="2015-11-30T22:47:07Z" finished-at="2015-11-30T22:47:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test004login -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:projects.ticket.testCases.ticketWeb.baShi@5594a1b5]" name="tearDown" is-config="true" duration-ms="1780" started-at="2015-11-30T22:47:09Z" finished-at="2015-11-30T22:47:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- projects.ticket.testCases.ticketWeb.baShi -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
